# Small, dependency-light helper functions shared across the pipeline:
# prompt formatting, cleaning up raw LLM output, and one-off dataset
# de-duplication utilities used while building dataset/personas.csv and
# dataset/tasks.csv from the raw paraphrases_personas_14May.csv survey export.

def ensure_python_prompt(prompt:str):
    """Wrap a task+persona prompt with instructions that force a Python-only,
    code-only response.

    LLMs frequently wrap code in markdown fences or add explanatory prose
    around it; since the downstream pipeline writes the raw response straight
    to a .py file (see write_file.py) and runs static analysis on it, any
    non-code text would break parsing. This wrapper is prepended/appended
    around the caller's prompt to minimize that.
    """
    prefix = "Write Python code."
    postfix = "Output only Python code and nothing else. CRITICAL:Do not include any markdown _or_ code block indicators."
    prompt = "\n".join([prefix, prompt, postfix])

    return prompt

import re
def remove_comments_and_docstrings(code: str) -> str:
    """Strip Python comments and docstrings from generated code before it's saved.

    This normalizes model output so that later complexity/security analysis
    (src/Complexity_metrics.py, static scanners) measures the actual code
    structure rather than being skewed by how verbosely a given model
    comments its own output.
    """
    # Remove all single-line comments (naive: does not special-case '#' inside
    # string literals, which is an accepted limitation for this dataset).
    code_no_single_line_comments = re.sub(r'#.*', '', code)

    # Remove all docstrings (both triple-double and triple-single quoted).
    code_no_docstrings = re.sub(r'""".*?"""', '', code_no_single_line_comments, flags=re.DOTALL)
    code_no_docstrings = re.sub(r"'''.*?'''", '', code_no_docstrings, flags=re.DOTALL)

    return code_no_docstrings

def clean_json(code:str)->str:
    """Strip markdown code-fence artifacts (```, ```json, and stray 'json' labels)
    that LLMs sometimes prepend to an otherwise-valid JSON response, so the
    remaining text can be parsed/saved as plain JSON by write_file.py.
    """
    code_docstring = re.sub(r'```.*?` ` `',"",code, flags=re.DOTALL)
    code_docstring = re.sub(r"```json","",code, flags=re.DOTALL)
    code_docstring = re.sub(r"json","",code, flags=re.DOTALL)

    return code_docstring


import pandas as pd
def count_persona():
    """Count how many rows of dataset/paraphrases_personas_14May.csv are tagged
    with each of the three personas used in this study (john, harold, brad).
    A one-off sanity check for dataset balance, not used by the main pipeline.
    """
    csv = pd.read_csv("dataset/paraphrases_personas_14May.csv")
    brad_count = 0
    john_count = 0
    harold_count = 0

    for row in csv.itertuples():

        if "john" in row.persona.lower():
            john_count += 1
        elif "harold" in row.persona.lower():
            harold_count += 1
        elif "brad" in row.persona.lower():
            brad_count += 1

    return brad_count, john_count, harold_count


def remove_duplicates():
    """Collapse the raw paraphrases_personas_14May.csv survey export down to one
    row per unique (task, persona) pair and write it to personas.csv.

    This is a one-off dataset-preparation step: personas.csv (used by
    dataset/personas.csv / main.py) is meant to be regenerated by re-running
    this function only if the underlying paraphrase survey data changes.
    """
    df = pd.read_csv("dataset/paraphrases_personas_14May.csv")
    df_unique = df.drop_duplicates(subset=["original_phrase","persona"])

    print(df_unique.shape[0])

    df_unique.to_csv("personas.csv",index=False)
    return df_unique


def get_unique_task():
    """Extract the set of distinct coding-task phrases (ignoring persona) from
    paraphrases_personas_14May.csv and write them to tasks.csv.

    Companion to remove_duplicates(): that keeps one row per (task, persona)
    pair, this keeps one row per task only, for anywhere the pipeline needs
    the task list independent of persona (e.g. the complexity-ranking prompt
    in main.py's rank_prompt()).
    """
    df = pd.read_csv("dataset/paraphrases_personas_14May.csv")
    df_unique = df.drop_duplicates(subset=["original_phrase"])
    df_phrase = df_unique["original_phrase"]


    df_phrase.to_csv("tasks.csv",index=False)
    return df_phrase

# NOTE: this call runs immediately on import (module-level side effect), so
# simply importing src.util re-reads paraphrases_personas_14May.csv and
# overwrites tasks.csv. Comment this out if you only need the helper
# functions above without re-running the dataset extraction.
get_unique_task()